version: '3.1'
services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
